version: '3'
services:
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
    tests:
        environment:
            - CHOKIDAR_USEPOLLING=true
        container_name: tests
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        command: ["npm", "run", "test"]